version: '3.8'

services:
  ml-traffic-analyzer:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - POSTGRES_URL=postgresql://admin:password@postgres:5432/traffic_analyzer
    depends_on:
      - postgres
    volumes:
      - ./processed:/app/processed
      - ./backend/logs:/app/backend/logs
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: traffic_analyzer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
